include ../arch.mk

.SUFFIXES: .f90 .o

TARGET = common_test

OBJ = \
  common_test.o

OBJCommon = Common.o

all: $(OBJ)
	$(FC) $(FFLAGS) $(MKL) $(FFTW) $(LIBES) $(OBJ) $(OBJCommon) -o $(TARGET)

new:
	make clean
	make all
.f90.o: 
	$(FC) -c $(FFLAGS) $(FFTW) $(LIBES) $<
clean:
	rm -rf *.so
	rm -rf *.o
	rm -rf *.mod
	rm -rf *.exe
