##### fortran
# FC = ifort
# INCLUDE = -I/opt/intel/compilers_and_libraries_2020.2.254/linux/mkl/include/fftw -I/home/sangkookchoi/usr/finufft-2.0.2/include
# FFLAGS = -debug -g -CB -check bounds -traceback -check uninit -fp-model precise
# LDFLAGS = # -L
# LOADLIBES = -L/home/sangkookchoi/usr/finufft-2.0.2/lib -lfinufft -lfftw3xf_intel -mkl 


FC = gfortran
INCLUDE = -I../finufft/include
#FFLAGS = -debug -g -CB -check bounds -traceback -check uninit -fp-model precise
FFLAGS = -DMPI -lblas -llapack
LDFLAGS = # -L
LOADLIBES = ../finufft/lib/libfinufft.so -lfftw3 -llapack
#LOADLIBES = ../finufft/lib/libfinufft.so -lfftw3 -mkl
LIBES = -L/opt/homebrew/opt/lapack/lib -llapack -lpthread -lm
FFTW = -I/opt/homebrew/opt/fftw/include
MKL = -I/opt/homebrew/opt/lapack/include
#LIBES = -L/home/momichael98/temp/Fortran/DiagE/modules/fftw3/fftw-3.3.10/lib -lfftw3 -mkl
#FFTW = -I/home/momichael98/temp/Fortran/DiagE/modules/fftw3/fftw-3.3.10/include
fortran2python = f2py -c --fcompiler=intelem --compiler=intelem $(LOADLIBES) $(INCLUDE)



