Crystal={'RVec': [[1,0,0],[0,1,0],[0,0,1]],
     'SOC': False,
     "CorF" : "F", # Cartesian or Fraction
     "Basis" : [[[0,0,0],1],[[0.5,0,0],1],[[0,0.5,0],1]], # d px py
     #'NOrb': [3,3], # Number of orbitals on basis sites
     'NSpin' : 1, # Spin option
     'NElec': 5.0, # The total number of electrons per spin -> 
     'KGrid': [10,10,1]
}
# FT = {
#      'T': 100,
#      'MatsubaraSize' : 1000
# }
    
### Combine TB and Coulomb to Hamiltonian ##
Hamiltonian = {
    'OneBody' : {
        'Hopping' : {
            ((0,0),(1,0)) : [2.15,[[0,0,0]]],
            ((0,0),(2,0)) : [2.15,[[0,0,0]]],
            ((1,0),(2,0)) : [1.00,[[0,0,0]]],
            ((1,0),(1,0)) : [0.2,[[-1,0,0]]],
            ((2,0),(2,0)) : [0.2,[[0,-1,0]]]
        },
        'Onsite' : {
            ((0,0)) : -5.92,
            ((0,1)) : 0,
            ((0,2)) : 0
        }
    },
    'TwoBody' : {
        'Local' : {
            "Parameter" : "SlaterKanamori", # Choose the parameterization of coulomb interaction (Slater, Kanamori,SlaterKanamori)
            "option" : {
                (0,(0)) : {
                    "l" : 0,
                    "U" : 10
                },
#                (1,(0)) : {
#                    "l" : 1,
#                    "U" : 10
#                },
#                (2,(0)) : {
#                    "l" : 1,
#                    "U" : 10
#                }
            }
                    },
        'NonLocal' : "None"
    }
}
Control= {
    'NSCF': 100,
    'Mix' : 0.1,
    'T': 300,
    'MatsubaraMesh' : 1000,
    'ConstantW' : 1.0,
    'Method' : 8, # 1 : TB, 2 : HF(H), 3 : HF(G), 4 : GW
}

