"""Solver-consistency guards for the BWeiss interaction served to PImp/WImp.

dyn.json collapses the correlated bath to one scalar D(nu) (the density-pair
average of ``cf``) coupled to the total density, so the impurity chi was
generated by ``v + D(nu)`` on every density pair.  ``f_to_solver`` must
reconstruct exactly that interaction (gw_edmft_v208 edmft.py:2727,
FullGWEDMFT Boson.F read_Uijkl_gname) instead of handing PImp/WImp the full
matrix Weiss field the solver never saw.
"""

from types import SimpleNamespace

import numpy as np

from QAssemble.BLocDyn import BWeiss


class _FakeProjector:
    """Two fermionic orbitals -> 4 bosonic pairs; density pairs are 0 and 3."""

    def __init__(self):
        norbb = 4
        self.bprojector = {"1": np.ones((1, norbb, norbb), dtype=float)}
        self.equiv = {"1": np.eye(norbb, dtype=int)}
        self.blocal2pair = {"1": [{0: (0, 0), 1: (0, 1), 2: (1, 0), 3: (1, 1)}]}
        self._pair2borb = {(0, 0): 0, (0, 1): 1, (1, 0): 2, (1, 1): 3}

    def ProbFPair2Borb(self, key, iorb, jorb, ispace=0):
        return self._pair2borb[(iorb, jorb)]


def _build_bweiss(cf, cf_uniform, v):
    obj = object.__new__(BWeiss)
    obj.projector = _FakeProjector()
    obj.key = "1"
    obj.vloc = SimpleNamespace(vproj={"1": v})
    obj.cf = cf
    obj.cf_uniform = cf_uniform
    obj.cf_to_solver = None
    obj.cf_to_solver_uniform = None
    obj.f_to_solver = None
    obj.f_to_solver_uniform = None
    obj._build_solver_consistent()
    return obj


def _make_v(norbb=4):
    v = np.zeros((norbb, norbb, 1, 1), dtype=np.complex128, order="F")
    v[0, 0, 0, 0] = 1.0
    v[3, 3, 0, 0] = 1.0
    v[0, 3, 0, 0] = v[3, 0, 0, 0] = 0.1
    return v


def test_uniform_density_block_degenerates_to_f():
    nfreq = 3
    v = _make_v()
    cf = np.zeros((4, 4, 1, 1, nfreq), dtype=np.complex128, order="F")
    for ib in (0, 3):
        for jb in (0, 3):
            cf[ib, jb, 0, 0, :] = np.array([-0.4, -0.2, -0.1])

    obj = _build_bweiss(cf, cf_uniform=cf.copy(), v=v)

    np.testing.assert_allclose(obj.cf_to_solver, [-0.4, -0.2, -0.1])
    expected_f = np.broadcast_to(v[..., np.newaxis], cf.shape) + cf
    np.testing.assert_allclose(obj.f_to_solver, expected_f)


def test_spread_density_block_gets_average_and_leaves_bare_elsewhere():
    nfreq = 2
    v = _make_v()
    cf = np.zeros((4, 4, 1, 1, nfreq), dtype=np.complex128, order="F")
    cf[0, 0, 0, 0, :] = -0.12
    cf[3, 3, 0, 0, :] = -0.10
    cf[0, 3, 0, 0, :] = cf[3, 0, 0, 0, :] = -0.05
    # Non-density pairs carry matrix-Dyson structure the solver never saw;
    # it must not leak into the reconstruction.
    cf[1, 1, 0, 0, :] = 0.7
    cf[1, 2, 0, 0, :] = -0.3

    obj = _build_bweiss(cf, cf_uniform=cf.copy(), v=v)

    mean = (-0.12 - 0.10 - 0.05 - 0.05) / 4.0
    np.testing.assert_allclose(obj.cf_to_solver, [mean, mean])
    for ib in (0, 3):
        for jb in (0, 3):
            np.testing.assert_allclose(
                obj.f_to_solver[ib, jb, 0, 0, :], v[ib, jb, 0, 0].real + mean
            )
    # Everything off the density block is the bare interaction only.
    np.testing.assert_allclose(obj.f_to_solver[1, 1, 0, 0, :], 0.0)
    np.testing.assert_allclose(obj.f_to_solver[1, 2, 0, 0, :], 0.0)


def test_as_dyn_dict_shares_the_solver_scalar():
    nfreq = 2
    v = _make_v()
    cf = np.zeros((4, 4, 1, 1, nfreq), dtype=np.complex128, order="F")
    cf[0, 0, 0, 0, :] = -0.2
    cf_uniform = cf * 2.0

    obj = _build_bweiss(cf, cf_uniform=cf_uniform, v=v)
    dyn = obj._as_dyn_dict("1")

    np.testing.assert_allclose(dyn["1"], obj.cf_to_solver_uniform.real)
    # And the uniform average really came from cf_uniform, not cf.
    np.testing.assert_allclose(
        obj.cf_to_solver_uniform, 2.0 * obj.cf_to_solver
    )
